// AUTO-GENERATED from Vector's public API
// DO NOT EDIT - Generated by build.rs

use pyo3::prelude::*;
use pyo3::types::*;
use std::collections::BTreeMap;

/// Auto-generated binding for vector_core::event::LogEvent
#[pyclass]
#[derive(Clone)]
pub struct LogEvent {
    // Internal Vector type (not exposed to Python directly)
    #[pyo3(get, set)]
    pub data: String,  // Simplified for POC
}

#[pymethods]
impl LogEvent {
    #[new]
    pub fn new() -> Self {
        LogEvent {
            data: String::new(),
        }
    }

    pub fn __repr__(&self) -> String {
        format!("LogEvent(data={})", self.data)
    }

    // Auto-generated getters/setters would go here
    // In real implementation, use actual Vector API
}

/// Auto-generated binding for vector_core::event::Event
#[pyclass]
#[derive(Clone)]
pub struct Event {
    variant: String,
}

#[pymethods]
impl Event {
    #[staticmethod]
    pub fn log() -> Self {
        Event {
            variant: "Log".to_string(),
        }
    }

    #[staticmethod]
    pub fn metric() -> Self {
        Event {
            variant: "Metric".to_string(),
        }
    }

    #[staticmethod]
    pub fn trace() -> Self {
        Event {
            variant: "Trace".to_string(),
        }
    }

    pub fn __repr__(&self) -> String {
        format!("Event::{}", self.variant)
    }

    pub fn variant_name(&self) -> String {
        self.variant.clone()
    }
}

/// Auto-generated binding for vector_core::event::Metric
#[pyclass]
#[derive(Clone)]
pub struct Metric {
    // Internal Vector type (not exposed to Python directly)
    #[pyo3(get, set)]
    pub data: String,  // Simplified for POC
}

#[pymethods]
impl Metric {
    #[new]
    pub fn new() -> Self {
        Metric {
            data: String::new(),
        }
    }

    pub fn __repr__(&self) -> String {
        format!("Metric(data={})", self.data)
    }

    // Auto-generated getters/setters would go here
    // In real implementation, use actual Vector API
}


/// Register all auto-discovered Vector APIs
pub fn register_all_auto_bindings(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<LogEvent>()?;
    m.add_class::<Event>()?;
    m.add_class::<Metric>()?;
    Ok(())
}
